{{- if and (.Values.pegasearch.externalSearchService) ((.Values.pegasearch.srsAuth).enabled) (not .Values.pegasearch.srsAuth.external_secret_name) }}
# Secret for OAuth private key used to get an authorization token for Pega Infinity connection to Search and Reporting Service
apiVersion: v1
kind: Secret
metadata:
  name: pega-srs-auth-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  privateKey: {{ template "srsAuthPrivateKey" . }}
{{- end }}
